config/routes.rb
Rails.application.routes.draw do

  root to: 'root#index'

  namespace :auth do
    get :login
    get :sign_up
    get :logout

    post :authenticate
    post :register
  end

  def level_paths
    (1..5).map do |index|
      (1..index).map{|k| ":level#{k}" }.join(?/)
    end
  end

  # Angular States
  namespace :states do
    level_paths.each do |path|
      get path, to: 'root#index'
    end
  end

  namespace :api do
    namespace :v1 do
      resource :stats, only: :show

      namespace :collage do
        get :options
        get :search
        get :make
      end

      namespace :external_accounts do
        get ':external_account_id/connect', action: :connect, as: :connect
        get :callback, action: :callback, as: :callback
      end

      namespace :external_collections do
        get ':external_account_id/:linked_account_id/sync/:external_collection_id', action: :sync, as: :sync
      end
    end
  end

end

app/views/shared/_footer.slim
span
  | &copy; Vitaly Tarasenko aka Tarvit

app/views/shared/_header.slim
md-toolbar
  .md-toolbar-tools
    = link_to root_path do
      #logo
        = image_tag '/pics/incollage_logo_w.png'
    div flex=""
    - if authorized?
      .user-block layout="row" layout-align="center center"
        .username
          strong= current_user.username
        span
          = link_to auth_logout_path
            md-button.md-icon-button aria-label="Log out"
              md-icon md-font-library="material-icons" exit_to_app